version: '3.8'

services:
  # Product DB
  mariadb-product:
    image: mariadb:11
    container_name: mariadb-product
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: productdb
    ports:
      - "3307:3306"
    networks:
      - microservice-net

  # Customer DB
  mariadb-customer:
    image: mariadb:11
    container_name: mariadb-customer
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: customerdb
    ports:
      - "3308:3306"
    networks:
      - microservice-net

  # Order DB
  mariadb-order:
    image: mariadb:11
    container_name: mariadb-order
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: orderdb
    ports:
      - "3309:3306"
    networks:
      - microservice-net

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - microservice-net

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservice-net

networks:
  microservice-net:
    driver: bridge